### ISSUE TITLE
斎藤ちはる

### ISSUE THREAD

**Issue by re-fort** [re-fort/NgzkBlogArchive#13]

**Comment by hmumixaM** [comment]
Hi, re-fort! I love your website! Thank you so much for your nogizaka blog backup! Would you prepare to add 斎藤ちはる and 相楽伊織 in your website? Also, I think it will be great to have previous graduated members. I found the following two websites have data stored, though it will a little bit harder to crawl them :-( 

1. https://nogizaka46-dc.com/blog/
2. https://web.archive.org/web/20130515000000*/http://blog.nogizaka46.com/yukina.kashiwa/

**Comment by re-fort** [comment]
Hi, @hmumixaM 
I'm glad to hear your nice word!
Yes, I'm supposed to do so.

> I think it will be great to have previous graduated members

It sounds nice :)
Combing some snapshots provided by the latter link you mentioned, it might be accomplished.
I think crawling is not a problem only if HTML tree structure is same as current official blog.
I'll try to make yukina's archive in a few days.
