### ISSUE TITLE
突然すみません．．．．

### ISSUE THREAD

**Issue by ARATAYOKOYAMA** [re-fort/NgzkBlogArchive#3]
素敵なプロダクトを作成していただき，ありがとうございます！
中元日芽香さんと伊藤万理華さんのブログがクローズになることが決まりましたが，2人の追加はございますでしょうか．．．？

**Comment by re-fort** [comment]
@ARATAYOKOYAMA 
ありがとうございます！
はい、クローズ後に追加する予定です〜

**Comment by ARATAYOKOYAMA** [comment]
ありがとうございます！

**Comment by re-fort** [comment]
ブログ追加のタスクは#4, #5で扱いますので、このissueはクローズさせてもらいます〜

**Comment by sacoll** [comment]
コメント失礼致しますm(__)m 西野七瀬、若月佑美、能條愛未のブログの追加予定はございますでしょうか

**Comment by sacoll** [comment]
お返事ありがとうございます。よろしくお願い致しますm(__)m
